const { ChartJSNodeCanvas } = require("chartjs-node-canvas");
const { formatDate } = require("../../../libs/formatDate");
const { getAttendanceText } = require("../../../libs/reportHelper");

const buildChartImage = async (scoreRows) => {
  const labels = scoreRows.map((r) => r.name);
  const data = scoreRows.map((r) => r.score ?? 0);
  const chartJSNodeCanvas = new ChartJSNodeCanvas({ width: 500, height: 200, backgroundColour: "white" });
  return await chartJSNodeCanvas.renderToBuffer({
    type: "bar",
    data: { labels, datasets: [{ data, backgroundColor: "#3b82f6", borderRadius: 6 }] },
    options: { plugins: { legend: { display: false } }, scales: { y: { beginAtZero: true } } },
  });
};

const attendanceColorMap = { present: "#16a34a", absent: "#dc2626", late: "#f59e0b", excused: "#2563eb" };

const buildPDFDefinition = async (member, score, attendance, activity, year, quarter, rank, rankColor) => {
  const chartBase64 = `data:image/png;base64,${(await buildChartImage(score.rows)).toString("base64")}`;

  const scoreTableBody = [
    [{ text: "Mon", bold: true, fontSize: 10, fillColor: "#f1f5f9", alignment: "center" }, { text: "Diem", bold: true, fontSize: 10, fillColor: "#f1f5f9", alignment: "center" }, { text: "He so", bold: true, fontSize: 10, fillColor: "#f1f5f9", alignment: "center" }, { text: "Quy doi", bold: true, fontSize: 10, fillColor: "#f1f5f9", alignment: "center" }],
    ...score.rows.map((r) => [{ text: r?.name || "", fontSize: 10, alignment: "center" }, { text: r?.score != null ? String(r.score) : "", fontSize: 10, alignment: "center" }, { text: r?.weight != null ? String(r.weight) : "", fontSize: 10, alignment: "center" }, { text: r ? r.weighted.toFixed(1) : "", fontSize: 10, alignment: "center" }]),
  ];

  const attendanceTableBody = [
    [{ text: "Ngay", bold: true, fontSize: 10, fillColor: "#f1f5f9", alignment: "center" }, { text: "Trang thai", bold: true, fontSize: 10, fillColor: "#f1f5f9", alignment: "center" }, { text: "Ghi chu", bold: true, fontSize: 10, fillColor: "#f1f5f9", alignment: "center" }],
    ...attendance.list.map((a) => [{ text: a ? formatDate(a.date) : "", fontSize: 9, alignment: "center" }, { text: a ? getAttendanceText(a.status) : "", fontSize: 9, alignment: "center", color: a ? (attendanceColorMap[a.status] || "#000") : "#000" }, { text: a?.note || "", fontSize: 9, alignment: "center" }]),
  ];

  const activityTableBody = [
    [{ text: "Ten hoat dong", bold: true, fontSize: 10, fillColor: "#f1f5f9", alignment: "center" }, { text: "Ngay", bold: true, fontSize: 10, fillColor: "#f1f5f9", alignment: "center" }, { text: "Trang thai", bold: true, fontSize: 10, fillColor: "#f1f5f9", alignment: "center" }],
    ...activity.list.map((a) => [{ text: a?.activity?.name || "", fontSize: 10, alignment: "center" }, { text: a ? formatDate(a.activity.date) : "", fontSize: 10, alignment: "center" }, { text: a?.status || "", fontSize: 10, alignment: "center" }]),
  ];

  return {
    pageSize: "A4",
    pageMargins: [30, 30, 30, 40],
    footer: (currentPage) => ({ columns: [{ text: "He thong quan ly doan sinh", fontSize: 9, color: "#64748b" }, { text: "Quarterly Report", fontSize: 9, color: "#64748b", alignment: "center" }, { text: `Trang ${currentPage}  -  ${new Date().toLocaleDateString("vi-VN")}`, fontSize: 9, color: "#64748b", alignment: "right" }], margin: [30, 0, 30, 0] }),
    content: [
      { canvas: [{ type: "rect", x: 0, y: 0, w: 535, h: 50, r: 6, color: "#3b82f6" }], margin: [0, 0, 0, -45] },
      { stack: [{ text: `BAO CAO DOAN SINH - Q${quarter}/${year}`, fontSize: 16, bold: true, color: "white" }, { text: "Member Performance Report - Generated by System", fontSize: 10, color: "#dbeafe" }], margin: [10, 5, 0, 16] },
      { columns: [{ stack: [{ text: member.name, fontSize: 13, bold: true, color: "#0f172a", margin: [0, 0, 0, 6] }, { text: `Ngay sinh: ${formatDate(member.birthDate)}`, fontSize: 10, color: "#334155", margin: [0, 2, 0, 2] }, { text: `Xa dao: ${member.parish || "-"}`, fontSize: 10, color: "#334155", margin: [0, 2, 0, 2] }, { text: `Nam vao doan: ${member.startYear || "-"}`, fontSize: 10, color: "#334155", margin: [0, 2, 0, 2] }], width: "50%" }, { columns: [{ stack: [{ text: "Diem TB", fontSize: 9, color: "#64748b", alignment: "center" }, { text: score.total.toFixed(2), fontSize: 14, bold: true, alignment: "center" }], width: "*" }, { stack: [{ text: "Xep loai", fontSize: 9, color: "#64748b", alignment: "center" }, { text: rank, fontSize: 13, bold: true, alignment: "center", color: rankColor }], width: "*" }, { stack: [{ text: "Co mat", fontSize: 9, color: "#64748b", alignment: "center" }, { text: `${attendance.summary.present}`, fontSize: 14, bold: true, alignment: "center" }], width: "*" }, { stack: [{ text: "Hoat dong", fontSize: 9, color: "#64748b", alignment: "center" }, { text: `${activity.summary.joined}/${activity.summary.total}`, fontSize: 14, bold: true, alignment: "center" }], width: "*" }], columnGap: 6, width: "50%" }], columnGap: 12, margin: [0, 0, 0, 10] },
      { text: "Bieu do diem", fontSize: 12, bold: true, color: "#1e293b", margin: [0, 0, 0, 6] },
      { image: chartBase64, width: 510, margin: [0, 0, 0, 12] },
      { columns: [{ stack: [{ text: "Chi tiet diem", fontSize: 12, bold: true, color: "#1e293b", margin: [0, 0, 0, 6] }, { table: { headerRows: 1, widths: ["*", "auto", "auto", "auto"], body: scoreTableBody }, layout: "lightHorizontalLines" }], width: "48%" }, { stack: [{ text: "Diem danh", fontSize: 12, bold: true, color: "#1e293b", margin: [0, 0, 0, 6] }, { table: { headerRows: 1, widths: ["auto", "auto", "*"], body: attendanceTableBody }, layout: "lightHorizontalLines" }], width: "52%" }], columnGap: 12, margin: [0, 0, 0, 10] },
      { stack: [{ text: "Hoat dong", fontSize: 12, bold: true, color: "#1e293b", margin: [0, 0, 0, 6] }, { table: { headerRows: 1, widths: ["*", "auto", "auto"], body: activityTableBody }, layout: "lightHorizontalLines" }], pageBreak: "before" },
    ],
    defaultStyle: { font: "Roboto" },
  };
};

module.exports = buildPDFDefinition;
