const fillRows = require("../../../libs/reportHelper").fillRows;
const {formatDate} = require("../../../libs/formatDate");
const getAttendanceText = require("../../../libs/reportHelper").getAttendanceText;
const getAttendanceColor = require("../../../libs/reportHelper").getAttendanceColor;

const buildHTML = (
  member,
  score,
  attendance,
  activity,
  year,
  quarter,
  rank,
  rankColor,
) => {
  const scoreRows = fillRows(score.rows, 7);
  const attendanceRows = fillRows(attendance.list, 12);
  const activityRows = fillRows(activity.list, 6);

  return `
  <html>
  <head>
    <meta charset="utf-8"/>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <style>
      * {
        box-sizing: border-box;
      }

      body {
        font-family: 'Segoe UI', sans-serif;
        background: #f1f5f9;
        margin: 0;
        padding: 0;
        -webkit-font-smoothing: antialiased;
      }

      /* A4 PAGE */
      .page {
        width: 794px;
        min-height: 1123px;
        margin: auto;
        padding: 20px;

        display: flex;
        flex-direction: column;
      }

      .content {
        flex: 1;
      }

      .page-break {
        page-break-before: always;
      }

      .avoid-break {
        page-break-inside: avoid;
      }

      /* HEADER */
      .header {
        display: flex;
        align-items: center;
        gap: 15px;
        background: linear-gradient(135deg, #3b82f6, #6366f1);
        color: white;
        padding: 16px;
        border-radius: 12px;
        margin-bottom: 16px;
      }

      .logo {
        width: 50px;
        height: 50px;
        object-fit: contain;
        background: white;
        border-radius: 8px;
        padding: 5px;
      }

      .header-title {
        font-size: 18px;
        font-weight: bold;
      }

      .sub-title {
        font-size: 12px;
        opacity: 0.9;
      }

      /* GRID */
      .grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 16px;
      }

      .full {
        grid-column: span 2;
      }

      .card {
        background: white;
        border-radius: 12px;
        padding: 14px;
        box-shadow: 0 4px 12px rgba(0,0,0,0.06);
      }

      /* PROFILE */
      .profile h2 {
        margin: 0 0 10px 0;
        font-size: 18px;
      }

      .profile p {
        margin: 6px 0;
        font-size: 14px;
        color: #334155;
        display: flex;
        gap: 6px;
      }

      .profile span {
        font-weight: 500;
        color: #0f172a;
      }

      /* STATS */
      .stats {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 10px;
      }

      .stat-box {
        background: #f8fafc;
        border-radius: 10px;
        padding: 10px;
        text-align: center;
      }

      .stat-box b {
        font-size: 15px;
      }

      .rank {
        display: inline-block;
        padding: 4px 10px;
        border-radius: 20px;
        color: white;
        font-size: 12px;
      }

      /* TABLE */
      table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 8px;
      }

      th {
        background: #f1f5f9;
      }

      th, td {
        border: 1px solid #e2e8f0;
        padding: 6px;
        font-size: 12px;
        text-align: center;
      }

      .section-title {
        font-size: 14px;
        font-weight: 600;
        margin-bottom: 5px;
      }

      canvas {
        max-height: 200px;
      }

      /* FOOTER */
      .footer {
        border-top: 1px solid #e2e8f0;
        padding-top: 8px;
        font-size: 11px;
        color: #64748b;

        display: flex;
        align-items: center;
        justify-content: space-between;
      }

      .footer .center {
        flex: 1;
        text-align: center;
        opacity: 0.8;
      }

      .footer .left {
        font-weight: 500;
      }

      .footer .right {
        text-align: right;
      }

      @media print {
        body {
          background: white;
        }
      }
    </style>
  </head>

  <body>

    <!-- PAGE 1 -->
    <div class="page">

      <div class="content">

        <!-- HEADER -->
        <div class="header">
          <img src="https://res.cloudinary.com/dmpru0wgq/image/upload/v1773730512/h5bpzxxhk907r1fgkfhm.png" class="logo"/>
          <div>
            <div class="header-title">
              BÁO CÁO ĐOÀN SINH - Q${quarter}/${year}
            </div>
            <div class="sub-title">
              Member Performance Report • Generated by System
            </div>
          </div>
        </div>

        <!-- GRID -->
        <div class="grid">

          <div class="card profile">
            <h2>${member.name}</h2>
            <p>📅 <span>Ngày sinh:</span> ${formatDate(member.birthDate)}</p>
            <p>⛪ <span>Xã đạo:</span> ${member.parish || "-"}</p>
            <p>📆 <span>Năm vào đoàn:</span> ${member.startYear || "-"}</p>
          </div>

          <div class="card">
            <div class="stats">
              <div class="stat-box">
                🎯 Điểm TB<br/>
                <b>${score.total.toFixed(2)}</b>
              </div>

              <div class="stat-box">
                🏆 Xếp loại<br/>
                <span class="rank" style="background:${rankColor}">
                  ${rank}
                </span>
              </div>

              <div class="stat-box">
                📅 Present<br/>
                <b>${attendance.summary.present}</b>
              </div>

              <div class="stat-box">
                🎉 Hoạt động<br/>
                <b>${activity.summary.joined}/${activity.summary.total}</b>
              </div>
            </div>
          </div>

          <!-- CHART -->
          <div class="card full avoid-break">
            <div class="section-title">📊 Biểu đồ điểm</div>
            <canvas id="chart"></canvas>
          </div>

          <!-- SCORE -->
          <div class="card">
            <div class="section-title">📊 Chi tiết điểm</div>
            <table>
              <tr>
                <th>Môn</th>
                <th>Điểm</th>
                <th>Hệ số</th>
                <th>Quy đổi</th>
              </tr>
              ${scoreRows.map(r => `
              <tr>
                <td>${r?.name || ""}</td>
                <td>${r?.score ?? ""}</td>
                <td>${r?.weight ?? ""}</td>
                <td>${r ? r.weighted.toFixed(1) : ""}</td>
              </tr>`).join("")}
            </table>
          </div>

          <!-- ATTENDANCE -->
          <div class="card avoid-break">
            <div class="section-title">📅 Điểm danh</div>
            <table>
              <tr>
                <th>Ngày</th>
                <th>Trạng thái</th>
                <th>Ghi chú</th>
              </tr>
              ${attendanceRows.map(a => `
              <tr>
                <td>${a ? formatDate(a.date) : ""}</td>
                <td style="color:${getAttendanceColor(a?.status)}">
                  ${a ? getAttendanceText(a.status) : ""}
                </td>
                <td>${a?.note || ""}</td>
              </tr>`).join("")}
            </table>
          </div>

        </div>
      </div>

      <!-- FOOTER PAGE 1 -->
      <div class="footer">
        <div class="left">📊 Hệ thống quản lý đoàn sinh</div>
        <div class="center">Quarterly Report</div>
        <div class="right">${new Date().toLocaleDateString("vi-VN")}</div>
      </div>

    </div>

    <!-- PAGE 2 -->
    <div class="page page-break">

      <div class="content">

        <div class="card">
          <div class="section-title">🎉 Hoạt động</div>
          <table>
            <tr>
              <th>Tên</th>
              <th>Ngày</th>
              <th>Trạng thái</th>
            </tr>
            ${activityRows.map(a => `
            <tr>
              <td>${a?.activity?.name || ""}</td>
              <td>${a ? formatDate(a.activity.date) : ""}</td>
              <td>${a?.status || ""}</td>
            </tr>`).join("")}
          </table>
        </div>

      </div>

      <!-- FOOTER PAGE 2 -->
      <div class="footer">
        <div class="left">📊 Hệ thống quản lý đoàn sinh</div>
        <div class="center">Activity Report</div>
        <div class="right">Page 2</div>
      </div>

    </div>

    <script>
      const ctx = document.getElementById('chart').getContext('2d');

      new Chart(ctx, {
        type: 'bar',
        data: {
          labels: ${JSON.stringify(score.rows.map(r => r.name))},
          datasets: [{
            data: ${JSON.stringify(score.rows.map(r => r.score))},
            backgroundColor: '#3b82f6',
            borderRadius: 6
          }]
        },
        options: {
          plugins: { legend: { display: false }},
          scales: { y: { beginAtZero: true }}
        }
      });
    </script>

  </body>
  </html>
  `;
};

module.exports = buildHTML;